#!/bin/sh

SCRIPT_PATH=$(readlink -f "$0" 2>/dev/null || realpath "$0" 2>/dev/null)
if [ -z "$SCRIPT_PATH" ]; then
    SCRIPT_PATH=$(cd "$(dirname "$0")" && pwd -P)/$(basename "$0")
fi
FAM_BASE=$(dirname "$(dirname "$SCRIPT_PATH")")

. ${FAM_BASE}/scripts/parse_params.sh "$@"

if [ ${CLEAN} -eq 1 ]; then
	. ${FAM_BASE}/scripts/clean.sh "$@"
elif [ ${COVERAGE} -eq 1 ]; then
	. ${FAM_BASE}/scripts/coverage.sh "$@"
elif [ ${TEST} -eq 1 ]; then
	. ${FAM_BASE}/scripts/test.sh "$@"
elif [ ${ALL} -eq 1 ]; then
	. ${FAM_BASE}/scripts/all.sh "$@"
else
	echo "Unepxected state - no option selected!";
	exit 1;
fi

